<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<WindowsSdkPackageVersion>10.0.19041.57</WindowsSdkPackageVersion>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<WindowsPackageType>None</WindowsPackageType>
		<OutputType>WinExe</OutputType>
		<RootNamespace>EightySixBoxManager</RootNamespace>
		<AssemblyName>_86Manager</AssemblyName>
		<MapFileExtensions>true</MapFileExtensions>
		<ApplicationRevision>0</ApplicationRevision>
		<ApplicationVersion>1.0.0.%2a</ApplicationVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<PropertyGroup>
		<ApplicationIcon>Resources\86Box-gray.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<COMReference Include="IWshRuntimeLibrary">
			<Guid>{F935DC20-1CF0-11D0-ADB9-00C04FD58A0B}</Guid>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<Lcid>0</Lcid>
			<WrapperTool>tlbimp</WrapperTool>
			<Isolated>False</Isolated>
			<EmbedInteropTypes>True</EmbedInteropTypes>
		</COMReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250401001" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Fluent86.Core\Fluent86.Core.csproj" />
	</ItemGroup>
</Project>